#!/usr/bin/env python3
"""Cluster spots from a filtered VMR residual-matrix H5AD."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

import anndata as ad
import igraph as ig
import leidenalg
import matplotlib
import numpy as np
import pandas as pd
import umap
from scipy import sparse
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from mpl_toolkits.axes_grid1.anchored_artists import AnchoredSizeBar

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.collections import PatchCollection
from matplotlib.patches import Rectangle


# Based on scripts/benchmark/saturation.py, with additional purple and yellow
# tones that remain clear over a grayscale tissue image.
CLUSTER_COLORS = (
    "#A73030",
    "#E64B35",
    "#2F5597",
    "#4DBBD5",
    "#CC79A7",
    "#7E57C2",
    "#F0E442",
    "#C5A3E0",
    "#D6A500",
    "#FFE082",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Filtered H5AD generated by 02-matrix-qc.py.",
    )
    parser.add_argument(
        "--n-components",
        type=int,
        default=10,
        help="PCA rank/components for imputation and clustering (default: 10).",
    )
    parser.add_argument(
        "--max-iterations",
        type=int,
        default=100,
        help="Maximum iterative-PCA imputation rounds (default: 100).",
    )
    parser.add_argument(
        "--min-gain",
        type=float,
        default=0.01,
        help=(
            "Stop when imputation MSE divided by the largest observed MSE is "
            "below this value (default: 0.01)."
        ),
    )
    parser.add_argument(
        "--n-neighbors",
        type=int,
        default=20,
        help="Nearest neighbors used for SNN and UMAP (default: 20).",
    )
    parser.add_argument(
        "--snn-prune",
        type=float,
        default=1 / 15,
        help="Discard SNN edges at or below this Jaccard weight (default: 1/15).",
    )
    parser.add_argument(
        "--resolution",
        type=float,
        default=1.0,
        help="Leiden RB-configuration resolution (default: 1).",
    )
    parser.add_argument(
        "--umap-min-dist",
        type=float,
        default=0.3,
        help="UMAP minimum distance (default: 0.3).",
    )
    parser.add_argument(
        "--spot-size-um",
        type=float,
        default=50.0,
        help="Side length in micrometers of spatial spot squares (default: 50).",
    )
    parser.add_argument(
        "--crop-margin-um",
        type=float,
        default=500.0,
        help="Margin around the spot bounding box in micrometers (default: 500).",
    )
    parser.add_argument(
        "--random-seed", type=int, default=42, help="Random seed (default: 42)."
    )
    args = parser.parse_args()
    if args.n_components < 2:
        parser.error("--n-components must be at least 2")
    if args.max_iterations < 1:
        parser.error("--max-iterations must be at least 1")
    if not 0 < args.min_gain < 1:
        parser.error("--min-gain must be greater than 0 and less than 1")
    if args.n_neighbors < 2:
        parser.error("--n-neighbors must be at least 2")
    if not 0 <= args.snn_prune < 1:
        parser.error("--snn-prune must be at least 0 and less than 1")
    if args.resolution <= 0:
        parser.error("--resolution must be greater than 0")
    if not 0 <= args.umap_min_dist <= 1:
        parser.error("--umap-min-dist must be between 0 and 1")
    if args.spot_size_um <= 0:
        parser.error("--spot-size-um must be greater than 0")
    if args.crop_margin_um < 0:
        parser.error("--crop-margin-um must be at least 0")
    return args


def load_residuals(matrix: sparse.spmatrix) -> np.ndarray:
    """Convert sparse residuals to dense float32, with absent entries as NaN."""
    residuals = matrix.tocsr(copy=True)
    residuals.sum_duplicates()
    if not np.isfinite(residuals.data).all():
        raise ValueError("The H5AD matrix contains non-finite residuals")
    residuals.eliminate_zeros()
    coordinates = residuals.tocoo()
    values = np.full(residuals.shape, np.nan, dtype=np.float32)
    values[coordinates.row, coordinates.col] = coordinates.data.astype(
        np.float32, copy=False
    )
    return values


def iterative_pca_impute(
    values: np.ndarray,
    n_components: int,
    max_iterations: int,
    min_gain: float,
    random_seed: int,
    block_size: int = 2048,
) -> tuple[np.ndarray, list[tuple[int, float, float]]]:
    missing = np.isnan(values)
    matrix = values.copy()
    matrix[missing] = 0.0
    history: list[tuple[int, float, float]] = []
    largest_mse = 0.0

    for iteration in range(1, max_iterations + 1):
        pca = PCA(
            n_components=n_components,
            svd_solver="randomized",
            random_state=random_seed,
        )
        scores = pca.fit_transform(matrix)
        squared_error = 0.0
        missing_count = 0

        for start in range(0, matrix.shape[1], block_size):
            end = min(start + block_size, matrix.shape[1])
            block_missing = missing[:, start:end]
            if not block_missing.any():
                continue
            reconstruction = scores @ pca.components_[:, start:end]
            current = matrix[:, start:end]
            delta = reconstruction[block_missing] - current[block_missing]
            squared_error += float(np.dot(delta, delta))
            missing_count += int(delta.size)
            current[block_missing] = reconstruction[block_missing]

        mse = squared_error / missing_count if missing_count else 0.0
        largest_mse = max(largest_mse, mse)
        relative_mse = mse / largest_mse if largest_mse else 0.0
        history.append((iteration, mse, relative_mse))
        print(f"Iterative PCA {iteration}: relative_mse={relative_mse:.6f}")
        if iteration > 1 and relative_mse < min_gain:
            break
    return matrix, history


def final_pca(matrix: np.ndarray, n_components: int, random_seed: int) -> np.ndarray:
    model = PCA(
        n_components=n_components,
        svd_solver="randomized",
        random_state=random_seed,
    )
    return model.fit_transform(matrix)


def nearest_neighbors(scores: np.ndarray, n_neighbors: int) -> np.ndarray:
    if n_neighbors >= len(scores):
        raise ValueError(
            f"--n-neighbors ({n_neighbors}) must be less than spots ({len(scores)})"
        )
    model = NearestNeighbors(n_neighbors=n_neighbors + 1, metric="euclidean")
    model.fit(scores)
    indices = model.kneighbors(return_distance=False)
    result = np.empty((len(scores), n_neighbors), dtype=int)
    for index, neighbors in enumerate(indices):
        without_self = neighbors[neighbors != index]
        if len(without_self) < n_neighbors:
            raise ValueError(f"Could not obtain {n_neighbors} neighbors for spot {index}")
        result[index] = without_self[:n_neighbors]
    return result


def build_snn(neighbors: np.ndarray, prune: float) -> ig.Graph:
    memberships: list[set[int]] = []
    inverse: dict[int, list[int]] = defaultdict(list)
    for node, row in enumerate(neighbors):
        members = set(int(item) for item in row)
        members.add(node)
        memberships.append(members)
        for member in members:
            inverse[member].append(node)

    shared: dict[tuple[int, int], int] = defaultdict(int)
    for nodes in inverse.values():
        for left_index, left in enumerate(nodes):
            for right in nodes[left_index + 1 :]:
                pair = (left, right) if left < right else (right, left)
                shared[pair] += 1

    edges: list[tuple[int, int, float]] = []
    for (left, right), intersection in shared.items():
        union = len(memberships[left]) + len(memberships[right]) - intersection
        weight = intersection / union
        if weight > prune:
            edges.append((left, right, weight))
    if not edges:
        raise ValueError(f"SNN graph has no edges after pruning at {prune:g}")

    graph = ig.Graph(
        n=len(neighbors),
        edges=[(left, right) for left, right, _ in edges],
        directed=False,
    )
    graph.es["weight"] = [weight for _, _, weight in edges]
    return graph


def leiden_clusters(
    graph: ig.Graph, resolution: float, random_seed: int
) -> np.ndarray:
    partition = leidenalg.find_partition(
        graph,
        leidenalg.RBConfigurationVertexPartition,
        weights="weight",
        resolution_parameter=resolution,
        n_iterations=-1,
        seed=random_seed,
    )
    membership = np.asarray(partition.membership, dtype=int)
    communities = []
    for raw_cluster in sorted(set(membership)):
        members = np.flatnonzero(membership == raw_cluster)
        communities.append((raw_cluster, len(members), int(members.min())))
    communities.sort(key=lambda item: (-item[1], item[2]))
    remap = {raw: new for new, (raw, _, _) in enumerate(communities)}
    return np.asarray([remap[item] for item in membership], dtype=int)


def run_umap(
    scores: np.ndarray, n_neighbors: int, min_dist: float, random_seed: int
) -> np.ndarray:
    model = umap.UMAP(
        n_neighbors=n_neighbors,
        n_components=2,
        metric="euclidean",
        min_dist=min_dist,
        random_state=random_seed,
        transform_seed=random_seed,
        n_jobs=1,
    )
    return model.fit_transform(scores)


def spatial_plot_data(
    adata: ad.AnnData,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, float]:
    required = {"pxl_row_in_fullres", "pxl_col_in_fullres"}
    missing = required - set(adata.obs.columns)
    if missing:
        raise ValueError(f"Missing spatial obs column(s): {', '.join(sorted(missing))}")

    spatial = adata.uns.get("spatial", {})
    if len(spatial) != 1:
        raise ValueError("Expected exactly one library under adata.uns['spatial']")
    library = next(iter(spatial.values()))
    image = np.asarray(library["images"]["hires"])
    scale = float(library["scalefactors"]["tissue_hires_scalef"])
    hires_pixel_size_um = float(library["metadata"]["hires_pixel_size_um"])
    if not np.isfinite(hires_pixel_size_um) or hires_pixel_size_um <= 0:
        raise ValueError("hires_pixel_size_um must be finite and greater than zero")
    x = adata.obs["pxl_col_in_fullres"].to_numpy(dtype=float) * scale
    y = adata.obs["pxl_row_in_fullres"].to_numpy(dtype=float) * scale
    return image, x, y, hires_pixel_size_um


def cluster_colors(cluster_count: int) -> list[tuple[float, float, float, float]]:
    if cluster_count <= len(CLUSTER_COLORS):
        return [
            matplotlib.colors.to_rgba(color)
            for color in CLUSTER_COLORS[:cluster_count]
        ]
    palette = plt.get_cmap("turbo")
    return [
        palette(index / max(1, cluster_count - 1))
        for index in range(cluster_count)
    ]


def add_cluster_squares(
    axis: plt.Axes,
    clusters: np.ndarray,
    x: np.ndarray,
    y: np.ndarray,
    side_length: float,
) -> None:
    colors = cluster_colors(int(clusters.max()) + 1)
    half_size = side_length / 2
    squares = [
        Rectangle(
            (x_coordinate - half_size, y_coordinate - half_size),
            side_length,
            side_length,
        )
        for x_coordinate, y_coordinate in zip(x, y, strict=True)
    ]
    axis.add_collection(
        PatchCollection(
            squares,
            facecolors=[colors[item] for item in clusters],
            edgecolors="none",
        )
    )


def add_scale_bar(
    axis: plt.Axes,
    view_width_pixels: float,
    view_height_pixels: float,
    pixel_size_um: float,
) -> None:
    target_length_um = view_width_pixels * pixel_size_um / 5
    magnitude = 10 ** np.floor(np.log10(target_length_um))
    scale_bar_um = max(
        multiplier * magnitude
        for multiplier in (1, 2, 5)
        if multiplier * magnitude <= target_length_um
    )
    scale_bar = AnchoredSizeBar(
        axis.transData,
        scale_bar_um / pixel_size_um,
        f"{scale_bar_um:g} µm",
        loc="lower left",
        pad=0.4,
        borderpad=0.5,
        sep=3,
        frameon=True,
        size_vertical=max(2, view_height_pixels * 0.003),
        color="white",
    )
    scale_bar.patch.set_facecolor("black")
    scale_bar.patch.set_alpha(0.6)
    scale_bar.patch.set_edgecolor("none")
    axis.add_artist(scale_bar)


def plot_umap(
    path: Path,
    embedding: np.ndarray,
    clusters: np.ndarray,
) -> None:
    colors = cluster_colors(int(clusters.max()) + 1)
    color_values = [colors[item] for item in clusters]
    figure, axis = plt.subplots(figsize=(5, 4))
    axis.scatter(
        embedding[:, 0], embedding[:, 1], c=color_values, s=13, linewidths=0
    )
    axis.set_title("UMAP of VMR residuals", fontsize=12)
    axis.set_xlabel("UMAP1", fontsize=10)
    axis.set_ylabel("UMAP2", fontsize=10)
    figure.tight_layout()
    figure.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_spatial(
    path: Path,
    clusters: np.ndarray,
    image: np.ndarray,
    x: np.ndarray,
    y: np.ndarray,
    hires_pixel_size_um: float,
    spot_size_um: float,
) -> None:
    figure, axis = plt.subplots(figsize=(7, 6))
    axis.imshow(image, cmap="gray", origin="upper")

    spot_size_pixels = spot_size_um / hires_pixel_size_um
    add_cluster_squares(axis, clusters, x, y, spot_size_pixels)
    axis.set_xlim(0, image.shape[1])
    axis.set_ylim(image.shape[0], 0)
    axis.set_aspect("equal")
    axis.set_title("Leiden clusters on tissue image", fontsize=12)
    add_scale_bar(axis, image.shape[1], image.shape[0], hires_pixel_size_um)
    axis.set_axis_off()

    figure.tight_layout()
    figure.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_spatial_cropped(
    path: Path,
    clusters: np.ndarray,
    image: np.ndarray,
    x: np.ndarray,
    y: np.ndarray,
    hires_pixel_size_um: float,
    spot_size_um: float,
    crop_margin_um: float,
) -> None:
    spot_size_pixels = spot_size_um / hires_pixel_size_um
    margin_pixels = crop_margin_um / hires_pixel_size_um
    half_size = spot_size_pixels / 2
    left = max(0.0, float(x.min()) - half_size - margin_pixels)
    right = min(float(image.shape[1]), float(x.max()) + half_size + margin_pixels)
    top = max(0.0, float(y.min()) - half_size - margin_pixels)
    bottom = min(float(image.shape[0]), float(y.max()) + half_size + margin_pixels)

    figure, axis = plt.subplots(figsize=(7, 6))
    axis.imshow(image, cmap="gray", origin="upper")
    add_cluster_squares(axis, clusters, x, y, spot_size_pixels)
    axis.set_xlim(left, right)
    axis.set_ylim(bottom, top)
    axis.set_aspect("equal")
    axis.set_title("Leiden clusters on cropped tissue image", fontsize=12)
    add_scale_bar(
        axis,
        right - left,
        bottom - top,
        hires_pixel_size_um,
    )
    axis.set_axis_off()
    figure.tight_layout()
    figure.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_spot_positions(
    path: Path,
    clusters: np.ndarray,
    array_rows: np.ndarray,
    array_columns: np.ndarray,
) -> None:
    figure, axis = plt.subplots(figsize=(6, 5))
    add_cluster_squares(axis, clusters, array_columns, array_rows, 0.8)
    padding = 0.75
    axis.set_xlim(array_columns.max() + padding, array_columns.min() - padding)
    axis.set_ylim(array_rows.max() + padding, array_rows.min() - padding)
    axis.set_aspect("equal")
    axis.set_title("Leiden clusters by array position", fontsize=12)
    axis.set_axis_off()
    figure.tight_layout()
    figure.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_imputation_history(
    path: Path,
    history: list[tuple[int, float, float]],
    min_gain: float,
) -> None:
    iterations = [row[0] for row in history]
    mse = [row[1] for row in history]
    relative_mse = [row[2] for row in history]
    figure, axes = plt.subplots(1, 2, figsize=(10, 4))
    axes[0].plot(iterations, mse, marker="o", color="#4DBBD5")
    axes[0].set_xlabel("Iteration", fontsize=10)
    axes[0].set_ylabel("MSE", fontsize=10)
    axes[0].set_title("Iterative-PCA imputation", fontsize=12)
    axes[1].plot(iterations, relative_mse, marker="o", color="#4DBBD5")
    axes[1].axhline(min_gain, color="#E64B35", linestyle="--", linewidth=1)
    axes[1].set_xlabel("Iteration", fontsize=10)
    axes[1].set_ylabel("MSE / maximum MSE", fontsize=10)
    axes[1].set_title("Relative convergence", fontsize=12)
    for axis in axes:
        axis.grid(alpha=0.2)
    figure.tight_layout()
    figure.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def main() -> None:
    args = parse_args()
    input_path = args.input.expanduser().resolve()
    if not input_path.is_file():
        raise SystemExit(f"Input H5AD does not exist: {input_path}")

    output_dir = input_path.parent.parent / "clustered"
    output_path = output_dir / f"{input_path.stem}.clustered.h5ad"
    umap_path = output_dir / f"{input_path.stem}.umap.png"
    spatial_path = output_dir / f"{input_path.stem}.spatial.png"
    cropped_spatial_path = output_dir / f"{input_path.stem}.spatial_cropped.png"
    spatial_only_path = output_dir / f"{input_path.stem}.spatial_only.png"
    convergence_path = output_dir / f"{input_path.stem}.imputation_convergence.png"
    for path in (
        output_path,
        umap_path,
        spatial_path,
        cropped_spatial_path,
        spatial_only_path,
        convergence_path,
    ):
        if path.exists():
            raise SystemExit(f"Output already exists: {path}")
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        adata = ad.read_h5ad(input_path)
        if args.n_components >= min(adata.n_obs, adata.n_vars):
            raise ValueError(
                "--n-components must be smaller than both spot and VMR counts"
            )
        image, x, y, hires_pixel_size_um = spatial_plot_data(adata)
        array_rows = adata.obs["array_row"].to_numpy(dtype=float)
        array_columns = adata.obs["array_col"].to_numpy(dtype=float)
        values = load_residuals(adata.X)
        values, history = iterative_pca_impute(
            values,
            args.n_components,
            args.max_iterations,
            args.min_gain,
            args.random_seed,
        )
        scores = final_pca(values, args.n_components, args.random_seed)
        del values
        neighbors = nearest_neighbors(scores, args.n_neighbors)
        graph = build_snn(neighbors, args.snn_prune)
        clusters = leiden_clusters(graph, args.resolution, args.random_seed)
        embedding = run_umap(
            scores, args.n_neighbors, args.umap_min_dist, args.random_seed
        )
    except (KeyError, OSError, ValueError) as error:
        raise SystemExit(str(error)) from error

    adata.obs["cluster"] = pd.Categorical([f"D{item}" for item in clusters])
    adata.obsm["X_pca"] = scores.astype(np.float32)
    adata.obsm["X_umap"] = embedding.astype(np.float32)
    plot_umap(umap_path, embedding, clusters)
    plot_spatial(
        spatial_path,
        clusters,
        image,
        x,
        y,
        hires_pixel_size_um,
        args.spot_size_um,
    )
    plot_spatial_cropped(
        cropped_spatial_path,
        clusters,
        image,
        x,
        y,
        hires_pixel_size_um,
        args.spot_size_um,
        args.crop_margin_um,
    )
    plot_spot_positions(
        spatial_only_path,
        clusters,
        array_rows,
        array_columns,
    )
    plot_imputation_history(convergence_path, history, args.min_gain)
    adata.write_h5ad(output_path)

    print(f"Wrote {output_path} with {int(clusters.max()) + 1} clusters")
    print(f"UMAP figure: {umap_path}")
    print(f"Spatial figure: {spatial_path}")
    print(f"Cropped spatial figure: {cropped_spatial_path}")
    print(f"Spatial-only figure: {spatial_only_path}")
    print(f"Imputation convergence: {convergence_path}")


if __name__ == "__main__":
    main()
