#!/usr/bin/env python3
"""Plot spatial CG methylation for hippocampal and neuronal marker genes."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

import anndata as ad
import matplotlib
import numpy as np
import pandas as pd
from scipy import sparse

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.collections import PatchCollection
from matplotlib.colors import LinearSegmentedColormap, Normalize
from matplotlib.patches import Rectangle
from mpl_toolkits.axes_grid1.anchored_artists import AnchoredSizeBar


LOW_METHYLATION_COLOR = "#4DBBD5"
HIGH_METHYLATION_COLOR = "#E64B35"
METHYLATION_CMAP = LinearSegmentedColormap.from_list(
    "marker_methylation",
    (LOW_METHYLATION_COLOR, "#FFFFFF", HIGH_METHYLATION_COLOR),
)


@dataclass(frozen=True)
class MarkerSpec:
    gene: str
    group: str
    description: str


@dataclass(frozen=True)
class MarkerResult:
    spec: MarkerSpec
    relation: str
    vmr_name: str
    values: np.ndarray


DEFAULT_MARKERS = (
    MarkerSpec("Fibcd1", "hippocampus", "CA1 pyramidal layer"),
    MarkerSpec("Rgs14", "hippocampus", "CA2 pyramidal neurons"),
    MarkerSpec("Grik4", "hippocampus", "CA3 pyramidal neurons"),
    MarkerSpec("Prox1", "hippocampus", "dentate gyrus granule cells"),
    MarkerSpec("Rbfox3", "neuron", "mature neurons (NeuN)"),
    MarkerSpec("Slc17a7", "neuron", "excitatory glutamatergic neurons"),
    MarkerSpec("Gad1", "neuron", "inhibitory GABAergic neurons"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help=(
            "Filtered methylation-fraction H5AD generated by 02-matrix-qc.py, "
            "or a directory containing exactly one *.filtered.h5ad file."
        ),
    )
    parser.add_argument(
        "--relation",
        choices=("gene", "promoter"),
        default="gene",
        help=(
            "Annotated VMR relation to plot (default: gene, i.e. gene body). "
            "The supplied filtered CG matrix has gene-body but no promoter VMRs "
            "for the built-in markers."
        ),
    )
    parser.add_argument(
        "--spot-size-um",
        type=float,
        default=50.0,
        help="Side length in micrometers of spatial spot squares (default: 50).",
    )
    parser.add_argument(
        "--crop-margin-um",
        type=float,
        default=500.0,
        help="Margin around the spot bounding box in micrometers (default: 500).",
    )
    args = parser.parse_args()
    if args.spot_size_um <= 0:
        parser.error("--spot-size-um must be greater than 0")
    if args.crop_margin_um < 0:
        parser.error("--crop-margin-um must be at least 0")
    return args


def resolve_input(path: Path) -> Path:
    path = path.expanduser().resolve()
    if path.is_file():
        return path
    if path.is_dir():
        candidates = sorted(path.glob("*.filtered.h5ad"))
        if len(candidates) == 1:
            return candidates[0]
        raise ValueError(
            f"Expected exactly one *.filtered.h5ad in {path}, found {len(candidates)}"
        )
    raise ValueError(f"Input H5AD or directory does not exist: {path}")


def relation_display_name(relation: str) -> str:
    return "gene body" if relation == "gene" else relation


def marker_vmr_indices(
    adata: ad.AnnData,
    gene: str,
    relation: str,
) -> np.ndarray:
    required = {"gene_name", "gene_relation"}
    missing = required - set(adata.var.columns)
    if missing:
        raise ValueError(
            "Missing VMR annotation column(s): " + ", ".join(sorted(missing))
        )

    target = gene.casefold()
    matches: list[int] = []
    for index, (names_raw, relations_raw) in enumerate(
        zip(adata.var["gene_name"], adata.var["gene_relation"], strict=True)
    ):
        names = str(names_raw).split(";")
        relations = str(relations_raw).split(";")
        if len(names) != len(relations):
            raise ValueError(
                "Misaligned gene_name/gene_relation annotations for VMR "
                f"{adata.var_names[index]}"
            )
        if any(
            name.casefold() == target and item_relation == relation
            for name, item_relation in zip(names, relations, strict=True)
        ):
            matches.append(index)
    return np.asarray(matches, dtype=int)


def vmr_methylation(
    matrix: sparse.spmatrix,
    vmr_index: int,
) -> np.ndarray:
    """Return one VMR's measured methylation fraction for every spot."""
    if not sparse.issparse(matrix):
        raise TypeError("The methylation matrix must be sparse")

    selected = matrix[:, [vmr_index]].tocsr(copy=True)
    selected.sum_duplicates()
    data = selected.data
    if data.size and (
        not np.isfinite(data).all() or data.min() < 0 or data.max() > 1
    ):
        raise ValueError("Marker VMR values must be finite fractions from 0 to 1")

    # Stored zeroes are measured zero methylation; absent sparse entries are missing.
    observed = np.diff(selected.indptr) > 0
    values = np.full(selected.shape[0], np.nan, dtype=float)
    values[observed] = data
    return values


def spatial_plot_data(
    adata: ad.AnnData,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, float]:
    required = {
        "array_row",
        "array_col",
        "pxl_row_in_fullres",
        "pxl_col_in_fullres",
    }
    missing = required - set(adata.obs.columns)
    if missing:
        raise ValueError(f"Missing spatial obs column(s): {', '.join(sorted(missing))}")

    spatial = adata.uns.get("spatial", {})
    if len(spatial) != 1:
        raise ValueError("Expected exactly one library under adata.uns['spatial']")
    library = next(iter(spatial.values()))
    image = np.asarray(library["images"]["hires"])
    scale = float(library["scalefactors"]["tissue_hires_scalef"])
    hires_pixel_size_um = float(library["metadata"]["hires_pixel_size_um"])
    if not np.isfinite(hires_pixel_size_um) or hires_pixel_size_um <= 0:
        raise ValueError("hires_pixel_size_um must be finite and greater than zero")
    x = adata.obs["pxl_col_in_fullres"].to_numpy(dtype=float) * scale
    y = adata.obs["pxl_row_in_fullres"].to_numpy(dtype=float) * scale
    return image, x, y, hires_pixel_size_um


def add_marker_squares(
    axis: plt.Axes,
    values: np.ndarray,
    x: np.ndarray,
    y: np.ndarray,
    side_length: float,
) -> None:
    observed = np.isfinite(values)
    half_size = side_length / 2
    squares = [
        Rectangle(
            (x_coordinate - half_size, y_coordinate - half_size),
            side_length,
            side_length,
        )
        for x_coordinate, y_coordinate in zip(x[observed], y[observed], strict=True)
    ]
    axis.add_collection(
        PatchCollection(
            squares,
            facecolors=METHYLATION_CMAP(values[observed]),
            edgecolors="none",
        )
    )


def add_scale_bar(
    axis: plt.Axes,
    view_width_pixels: float,
    view_height_pixels: float,
    pixel_size_um: float,
) -> None:
    target_length_um = view_width_pixels * pixel_size_um / 5
    magnitude = 10 ** np.floor(np.log10(target_length_um))
    scale_bar_um = max(
        multiplier * magnitude
        for multiplier in (1, 2, 5)
        if multiplier * magnitude <= target_length_um
    )
    scale_bar = AnchoredSizeBar(
        axis.transData,
        scale_bar_um / pixel_size_um,
        f"{scale_bar_um:g} µm",
        loc="lower left",
        pad=0.4,
        borderpad=0.5,
        sep=3,
        frameon=True,
        size_vertical=max(2, view_height_pixels * 0.003),
        color="white",
    )
    scale_bar.patch.set_facecolor("black")
    scale_bar.patch.set_alpha(0.6)
    scale_bar.patch.set_edgecolor("none")
    axis.add_artist(scale_bar)


def marker_title(result: MarkerResult) -> str:
    return f"{result.spec.gene}\n{result.vmr_name}"


def add_methylation_colorbar(figure: plt.Figure, axis: plt.Axes) -> None:
    scalar_map = plt.cm.ScalarMappable(
        norm=Normalize(vmin=0, vmax=1),
        cmap=METHYLATION_CMAP,
    )
    scalar_map.set_array([])
    colorbar = figure.colorbar(scalar_map, ax=axis, fraction=0.046, pad=0.04)
    colorbar.set_label("CG methylation", fontsize=10)


def plot_spatial(
    path: Path,
    result: MarkerResult,
    image: np.ndarray,
    x: np.ndarray,
    y: np.ndarray,
    hires_pixel_size_um: float,
    spot_size_um: float,
) -> None:
    figure, axis = plt.subplots(figsize=(7, 6))
    axis.imshow(image, cmap="gray", origin="upper")
    spot_size_pixels = spot_size_um / hires_pixel_size_um
    add_marker_squares(axis, result.values, x, y, spot_size_pixels)
    axis.set_xlim(0, image.shape[1])
    axis.set_ylim(image.shape[0], 0)
    axis.set_aspect("equal")
    axis.set_title(marker_title(result), fontsize=12)
    add_scale_bar(axis, image.shape[1], image.shape[0], hires_pixel_size_um)
    axis.set_axis_off()
    add_methylation_colorbar(figure, axis)
    figure.tight_layout()
    figure.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_spatial_cropped(
    path: Path,
    result: MarkerResult,
    image: np.ndarray,
    x: np.ndarray,
    y: np.ndarray,
    hires_pixel_size_um: float,
    spot_size_um: float,
    crop_margin_um: float,
) -> None:
    spot_size_pixels = spot_size_um / hires_pixel_size_um
    margin_pixels = crop_margin_um / hires_pixel_size_um
    half_size = spot_size_pixels / 2
    left = max(0.0, float(x.min()) - half_size - margin_pixels)
    right = min(float(image.shape[1]), float(x.max()) + half_size + margin_pixels)
    top = max(0.0, float(y.min()) - half_size - margin_pixels)
    bottom = min(float(image.shape[0]), float(y.max()) + half_size + margin_pixels)

    figure, axis = plt.subplots(figsize=(7, 6))
    axis.imshow(image, cmap="gray", origin="upper")
    add_marker_squares(axis, result.values, x, y, spot_size_pixels)
    axis.set_xlim(left, right)
    axis.set_ylim(bottom, top)
    axis.set_aspect("equal")
    axis.set_title(marker_title(result), fontsize=12)
    add_scale_bar(axis, right - left, bottom - top, hires_pixel_size_um)
    axis.set_axis_off()
    add_methylation_colorbar(figure, axis)
    figure.tight_layout()
    figure.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_spot_positions(
    path: Path,
    result: MarkerResult,
    array_rows: np.ndarray,
    array_columns: np.ndarray,
) -> None:
    figure, axis = plt.subplots(figsize=(6, 5))
    add_marker_squares(axis, result.values, array_columns, array_rows, 0.8)
    padding = 0.75
    axis.set_xlim(array_columns.max() + padding, array_columns.min() - padding)
    axis.set_ylim(array_rows.max() + padding, array_rows.min() - padding)
    axis.set_aspect("equal")
    axis.set_title(marker_title(result), fontsize=12)
    axis.set_axis_off()
    add_methylation_colorbar(figure, axis)
    figure.tight_layout()
    figure.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def output_stem(result: MarkerResult) -> str:
    gene = re.sub(r"[^A-Za-z0-9_.-]+", "_", result.spec.gene)
    vmr = re.sub(r"[^A-Za-z0-9_.-]+", "_", result.vmr_name)
    return f"{gene}.{result.relation}.{vmr}"


def main() -> None:
    args = parse_args()
    try:
        input_path = resolve_input(args.input)
    except ValueError as error:
        raise SystemExit(str(error)) from error

    output_dir = (
        input_path.parent.parent / "markers"
    )

    try:
        markers = DEFAULT_MARKERS
        adata = ad.read_h5ad(input_path)
        image, x, y, hires_pixel_size_um = spatial_plot_data(adata)
        results: list[MarkerResult] = []
        skipped: list[str] = []
        for marker in markers:
            indices = marker_vmr_indices(adata, marker.gene, args.relation)
            if not indices.size:
                skipped.append(marker.gene)
                continue
            for index in indices:
                values = vmr_methylation(adata.X, int(index))
                if not np.isfinite(values).any():
                    continue
                results.append(
                    MarkerResult(
                        spec=marker,
                        relation=args.relation,
                        vmr_name=str(adata.var_names[index]),
                        values=values,
                    )
                )
        if not results:
            raise ValueError(
                f"None of the requested genes has a measured {args.relation!r} VMR"
            )
    except (KeyError, OSError, ValueError) as error:
        raise SystemExit(str(error)) from error

    table_path = output_dir / "marker_methylation_by_spot.tsv"
    annotation_path = output_dir / "marker_vmr_annotations.tsv"
    figure_outputs: list[tuple[MarkerResult, tuple[Path, Path, Path]]] = []
    for result in results:
        marker_dir = output_dir / result.spec.group / result.spec.gene
        stem = output_stem(result)
        figure_outputs.append(
            (
                result,
                (
                    marker_dir / f"{stem}.spatial.png",
                    marker_dir / f"{stem}.spatial_cropped.png",
                    marker_dir / f"{stem}.spatial_only.png",
                ),
            )
        )
    all_figure_paths = [
        path for _, paths in figure_outputs for path in paths
    ]
    for path in (table_path, annotation_path, *all_figure_paths):
        if path.exists():
            raise SystemExit(f"Output already exists: {path}")

    output_dir.mkdir(parents=True, exist_ok=True)
    spot_table = pd.DataFrame({"spot": adata.obs_names.astype(str)})
    annotation_rows: list[dict[str, str]] = []
    for result in results:
        spot_table[f"{result.spec.gene}|{result.vmr_name}"] = result.values
        annotation_rows.append(
            {
                "gene": result.spec.gene,
                "group": result.spec.group,
                "description": result.spec.description,
                "relation": relation_display_name(result.relation),
                "vmr": result.vmr_name,
            }
        )
    spot_table.to_csv(table_path, sep="\t", index=False, na_rep="NA")
    pd.DataFrame(annotation_rows).to_csv(annotation_path, sep="\t", index=False)

    array_rows = adata.obs["array_row"].to_numpy(dtype=float)
    array_columns = adata.obs["array_col"].to_numpy(dtype=float)
    for result, paths in figure_outputs:
        spatial_path, cropped_path, spatial_only_path = paths
        spatial_path.parent.mkdir(parents=True, exist_ok=True)
        plot_spatial(
            spatial_path,
            result,
            image,
            x,
            y,
            hires_pixel_size_um,
            args.spot_size_um,
        )
        plot_spatial_cropped(
            cropped_path,
            result,
            image,
            x,
            y,
            hires_pixel_size_um,
            args.spot_size_um,
            args.crop_margin_um,
        )
        plot_spot_positions(
            spatial_only_path,
            result,
            array_rows,
            array_columns,
        )

    marker_counts = {
        marker.gene: sum(result.spec.gene == marker.gene for result in results)
        for marker in markers
    }
    print(
        "Markers: "
        + ", ".join(
            f"{gene} ({count} {relation_display_name(args.relation)} "
            f"VMR{'s' if count != 1 else ''})"
            for gene, count in marker_counts.items()
            if count
        )
    )
    print(f"VMR maps: {len(results):,}; figures: {len(all_figure_paths):,}")
    if skipped:
        print(
            f"Skipped without measured {relation_display_name(args.relation)} VMRs: "
            + ", ".join(skipped)
        )
    print(f"Methylation table: {table_path}")
    print(f"VMR annotations: {annotation_path}")
    print(f"Marker figures: {output_dir}")


if __name__ == "__main__":
    main()
