#!/usr/bin/env python3
"""Add GENCODE annotations to shared VMR features in an h5ad file."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import anndata as ad
import numpy as np
import pandas as pd
import pyranges as pr


VMR_PATTERN = re.compile(r"^(?P<chrom>[^:]+):(?P<start>\d+)-(?P<end>\d+)$")
GENE_ATTR_PATTERN = re.compile(
    r'gene_id "(?P<gene_id>[^"]+)";.*?'
    r'gene_type "(?P<gene_type>[^"]+)";.*?'
    r'gene_name "(?P<gene_name>[^"]+)";'
)
GTF_COLUMNS = (
    "chrom",
    "source",
    "feature",
    "start",
    "end",
    "score",
    "strand",
    "frame",
    "attr",
)
GENE_COLUMNS = (
    "gene_id",
    "gene_name",
    "gene_type",
    "gene_relation",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        dest="input_h5ad",
        type=Path,
        required=True,
        help="Combined residual/methylation H5AD generated by 00-matrix-IO.py.",
    )
    parser.add_argument(
        "--gtf",
        type=Path,
        required=True,
        help="GENCODE GTF, gzipped or plain text.",
    )
    args = parser.parse_args()
    return args


def read_genes(path: Path) -> pd.DataFrame:
    """Read GENCODE gene records as 0-based, half-open intervals."""
    frame = pd.read_csv(
        path,
        sep="\t",
        comment="#",
        header=None,
        names=GTF_COLUMNS,
        dtype=str,
        compression="gzip" if path.suffix == ".gz" else "infer",
    )
    genes = frame[frame["feature"] == "gene"].copy()
    if genes.empty:
        raise ValueError(f"No gene records found in {path}")

    attributes = genes["attr"].str.extract(GENE_ATTR_PATTERN)
    if attributes.isna().any().any():
        raise ValueError(f"Some gene records lack gene_id/type/name attributes: {path}")

    starts = genes["start"].astype(int) - 1
    ends = genes["end"].astype(int)
    return pd.DataFrame(
        {
            "Chromosome": genes["chrom"],
            "Start": starts,
            "End": ends,
            "gene_strand": genes["strand"],
            "gene_id": attributes["gene_id"],
            "gene_name": attributes["gene_name"],
            "gene_type": attributes["gene_type"],
        }
    )


def parse_vmr_regions(var_names: pd.Index) -> pd.DataFrame:
    """Parse genomic intervals from AnnData feature names."""
    rows: list[dict[str, str | int]] = []
    for feature in var_names.astype(str):
        match = VMR_PATTERN.fullmatch(feature)
        if match is None:
            raise ValueError(f"Invalid VMR feature name: {feature!r}")
        start = int(match.group("start"))
        end = int(match.group("end"))
        if end <= start:
            raise ValueError(f"Invalid VMR interval: {feature!r}")
        rows.append(
            {
                "Chromosome": match.group("chrom"),
                "Start": start,
                "End": end,
                "vmr": feature,
            }
        )
    return pd.DataFrame(rows)


def promoter_regions(
    genes: pd.DataFrame, upstream: int, downstream: int
) -> pd.DataFrame:
    promoters = genes.copy()
    is_plus = promoters["gene_strand"] == "+"
    tss = np.where(is_plus, promoters["Start"], promoters["End"] - 1)
    before_tss = np.where(is_plus, upstream, downstream)
    after_tss = np.where(is_plus, downstream, upstream)
    promoters["Start"] = np.maximum(0, tss - before_tss)
    promoters["End"] = tss + after_tss
    return promoters


def select_columns(frame: pd.DataFrame, relation: str) -> pd.DataFrame:
    selected = frame[["vmr", "gene_id", "gene_name", "gene_type"]].copy()
    selected["gene_relation"] = relation
    return selected


def annotate_vmrs(
    vmrs: pd.DataFrame,
    genes: pd.DataFrame,
    promoter_upstream: int,
    promoter_downstream: int,
) -> pd.DataFrame:
    """Associate VMRs with gene bodies, promoters, or the nearest gene."""
    gene_ranges = pr.PyRanges(genes)
    vmr_ranges = pr.PyRanges(vmrs)

    body = vmr_ranges.join(gene_ranges).df
    annotations: list[pd.DataFrame] = []
    annotated_vmrs: set[str] = set()
    if not body.empty:
        annotations.append(select_columns(body, "gene"))
        annotated_vmrs.update(body["vmr"])

    remaining = vmrs[~vmrs["vmr"].isin(annotated_vmrs)]
    if not remaining.empty:
        promoters = promoter_regions(genes, promoter_upstream, promoter_downstream)
        promoter_hits = pr.PyRanges(remaining).join(pr.PyRanges(promoters)).df
        if not promoter_hits.empty:
            annotations.append(select_columns(promoter_hits, "promoter"))
            annotated_vmrs.update(promoter_hits["vmr"])

    remaining = vmrs[~vmrs["vmr"].isin(annotated_vmrs)]
    if not remaining.empty:
        nearest = pr.PyRanges(remaining).nearest(gene_ranges).df
        if not nearest.empty:
            annotations.append(select_columns(nearest, "intergenic"))

    if not annotations:
        return pd.DataFrame(columns=GENE_COLUMNS, index=pd.Index([], name="vmr"))
    combined = pd.concat(annotations, ignore_index=True)
    combined = combined.drop_duplicates(["vmr", "gene_id"])
    return combined.groupby("vmr", sort=False)[list(GENE_COLUMNS)].agg(
        lambda values: ";".join(values.astype(str))
    )


def add_gene_annotations(
    adata: ad.AnnData,
    genes: pd.DataFrame,
    promoter_upstream: int,
    promoter_downstream: int,
) -> None:
    vmrs = parse_vmr_regions(adata.var_names)
    annotations = annotate_vmrs(
        vmrs,
        genes,
        promoter_upstream=promoter_upstream,
        promoter_downstream=promoter_downstream,
    ).reindex(adata.var_names)
    for column in GENE_COLUMNS:
        adata.var[column] = annotations[column].fillna("").to_numpy()


def main() -> None:
    args = parse_args()
    input_path = args.input_h5ad.expanduser().resolve()
    gtf_path = args.gtf.expanduser().resolve()
    output_path = input_path.parent / "add-gene" / f"{input_path.stem}.genes.h5ad"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if not input_path.is_file():
        raise SystemExit(f"Input H5AD does not exist: {input_path}")
    if not gtf_path.is_file():
        raise SystemExit(f"GTF does not exist: {gtf_path}")
    if output_path.exists():
        raise SystemExit(f"Output already exists: {output_path}")

    adata = ad.read_h5ad(input_path)
    genes = read_genes(gtf_path)
    add_gene_annotations(
        adata,
        genes,
        promoter_upstream=2000,
        promoter_downstream=500,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    adata.write_h5ad(output_path)
    print(
        f"Wrote {output_path} with gene annotations for "
        f"{adata.n_vars:,} VMRs"
    )


if __name__ == "__main__":
    main()
