#!/usr/bin/env python3
"""Filter residuals and methylation using an explicit observed-value mask."""

from __future__ import annotations

import argparse
from pathlib import Path

import anndata as ad
import matplotlib
import numpy as np
from scipy import sparse

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from utils import in_tissue_mask


METHYLATION_LAYER = "methylation"
VALUE_MASK_LAYER = "value_mask"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Annotated combined H5AD generated by 01-vmr-gene.py.",
    )
    parser.add_argument(
        "--min-vmrs-per-spot",
        type=int,
        default=1000,
        help="Minimum observed VMRs required to keep a spot (default: 1000).",
    )
    parser.add_argument(
        "--min-spots-per-vmr",
        type=int,
        default=10,
        help="Minimum retained spots required to keep a VMR (default: 10).",
    )
    args = parser.parse_args()
    if args.min_vmrs_per_spot < 1:
        parser.error("--min-vmrs-per-spot must be >= 1")
    if args.min_spots_per_vmr < 1:
        parser.error("--min-spots-per-vmr must be >= 1")
    return args


def observation_mask(matrix: sparse.spmatrix) -> sparse.csr_matrix:
    """Validate and normalize the explicit observed-value mask."""
    observed = matrix.tocsr(copy=True)
    observed.sum_duplicates()
    if not np.isfinite(observed.data).all():
        raise ValueError(f"The {VALUE_MASK_LAYER!r} layer contains non-finite values")
    if not np.isin(observed.data, (0, 1)).all():
        raise ValueError(f"The {VALUE_MASK_LAYER!r} layer must contain only 0 and 1")
    observed.eliminate_zeros()
    observed.data = np.ones(observed.nnz, dtype=np.uint8)
    return observed


def nonzero_counts(matrix: sparse.spmatrix, axis: int) -> np.ndarray:
    return np.asarray(matrix.getnnz(axis=axis)).ravel()


def filter_anndata(
    adata: ad.AnnData,
    min_vmrs_per_spot: int,
    min_spots_per_vmr: int,
) -> tuple[ad.AnnData, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    if adata.n_obs == 0 or adata.n_vars == 0:
        raise ValueError("The input H5AD matrix is empty")

    if not sparse.issparse(adata.X):
        raise ValueError("The residual matrix in X must be sparse")
    if METHYLATION_LAYER not in adata.layers:
        raise ValueError(f"The input H5AD is missing layer {METHYLATION_LAYER!r}")
    if not sparse.issparse(adata.layers[METHYLATION_LAYER]):
        raise ValueError(f"The {METHYLATION_LAYER!r} layer must be sparse")
    if VALUE_MASK_LAYER not in adata.layers:
        raise ValueError(f"The input H5AD is missing layer {VALUE_MASK_LAYER!r}")
    if not sparse.issparse(adata.layers[VALUE_MASK_LAYER]):
        raise ValueError(f"The {VALUE_MASK_LAYER!r} layer must be sparse")

    observed = observation_mask(adata.layers[VALUE_MASK_LAYER])
    tissue_spots = in_tissue_mask(adata)
    if not tissue_spots.any():
        raise ValueError("The input H5AD contains no spots marked as in tissue")

    tissue_observed = observed[tissue_spots]
    spot_counts = nonzero_counts(tissue_observed, axis=1)
    keep_tissue_spots = spot_counts >= min_vmrs_per_spot
    if not keep_tissue_spots.any():
        raise ValueError(
            "Spot filter removed every in-tissue spot at minimum support "
            f"{min_vmrs_per_spot}"
        )

    keep_spots = np.zeros(adata.n_obs, dtype=bool)
    keep_spots[np.flatnonzero(tissue_spots)[keep_tissue_spots]] = True

    vmr_counts = nonzero_counts(tissue_observed[keep_tissue_spots], axis=0)
    keep_vmrs = vmr_counts >= min_spots_per_vmr
    if not keep_vmrs.any():
        raise ValueError(
            "VMR filter removed every VMR at minimum support "
            f"{min_spots_per_vmr}"
        )

    return (
        adata[keep_spots, keep_vmrs].copy(),
        keep_spots,
        keep_vmrs,
        spot_counts,
        vmr_counts,
    )


def plot_filter_distributions(
    path: Path,
    spot_counts: np.ndarray,
    vmr_counts: np.ndarray,
    min_vmrs_per_spot: int,
    min_spots_per_vmr: int,
) -> None:
    figure, axes = plt.subplots(1, 2, figsize=(10, 4))
    panels = (
        (
            axes[0],
            spot_counts,
            min_vmrs_per_spot,
            "Observed VMRs per in-tissue spot",
            "VMRs",
            "Spots",
        ),
        (
            axes[1],
            vmr_counts,
            min_spots_per_vmr,
            "Observed spots per VMR",
            "Spots",
            "VMRs",
        ),
    )
    for axis, values, cutoff, title, xlabel, ylabel in panels:
        axis.hist(values, bins=100, color="#4DBBD5", edgecolor="white", linewidth=0.4)
        axis.axvline(cutoff, color="#E64B35", linestyle="--", linewidth=1.5)
        axis.set_title(title, fontsize=12)
        axis.set_xlabel(xlabel, fontsize=10)
        axis.set_ylabel(ylabel, fontsize=10)
        axis.grid(axis="y", alpha=0.2)
        axis.text(
            0.98,
            0.95,
            f"keep ≥ {cutoff:,}\nretained {int((values >= cutoff).sum()):,}/{len(values):,}",
            transform=axis.transAxes,
            ha="right",
            va="top",
        )
    figure.tight_layout()
    figure.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def main() -> None:
    args = parse_args()
    input_path = args.input.expanduser().resolve()
    if not input_path.is_file():
        raise SystemExit(f"Input H5AD does not exist: {input_path}")

    output_dir = input_path.parent.parent / "filtered"
    output_path = output_dir / f"{input_path.stem}.filtered.h5ad"
    figure_path = output_dir / f"{input_path.stem}.filter_distributions.png"
    if output_path.exists():
        raise SystemExit(f"Output already exists: {output_path}")
    if figure_path.exists():
        raise SystemExit(f"Output already exists: {figure_path}")
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        adata = ad.read_h5ad(input_path)
        filtered, keep_spots, keep_vmrs, spot_counts, vmr_counts = filter_anndata(
            adata,
            min_vmrs_per_spot=args.min_vmrs_per_spot,
            min_spots_per_vmr=args.min_spots_per_vmr,
        )
    except (OSError, ValueError) as error:
        raise SystemExit(str(error)) from error

    plot_filter_distributions(
        figure_path,
        spot_counts,
        vmr_counts,
        min_vmrs_per_spot=args.min_vmrs_per_spot,
        min_spots_per_vmr=args.min_spots_per_vmr,
    )
    filtered.write_h5ad(output_path)
    n_tissue_spots = len(spot_counts)
    print(
        f"Wrote {output_path}: "
        f"{adata.n_obs:,} -> {n_tissue_spots:,} in-tissue spots "
        f"({adata.n_obs - n_tissue_spots:,} outside-tissue spots removed) -> "
        f"{int(keep_spots.sum()):,} spots "
        f"(minimum {args.min_vmrs_per_spot:,} observed VMRs); "
        f"{adata.n_vars:,} -> {int(keep_vmrs.sum()):,} VMRs "
        f"(minimum {args.min_spots_per_vmr:,} observed spots)"
    )
    print(f"Filter distributions: {figure_path}")


if __name__ == "__main__":
    main()
