#!/usr/bin/env python3
"""Impute missing VMR methylation fractions after methylation clustering."""

from __future__ import annotations

import argparse
from pathlib import Path

import anndata as ad
import matplotlib
import numpy as np
from scipy import sparse
from sklearn.decomposition import PCA

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from utils import validate_output, write_anndata


METHYLATION_LAYER = "methylation"
IMPUTED_LAYER = "methylation_imputed"
VALUE_MASK_LAYER = "value_mask"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Clustered methylation H5AD generated by 03-cluster-methylation.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help=(
            "Output H5AD; defaults to "
            "<input-parent-parent>/imputed/<input-stem>.imputed.h5ad."
        ),
    )
    parser.add_argument(
        "--n-components",
        type=int,
        default=10,
        help="PCA rank used to impute methylation fractions (default: 10).",
    )
    parser.add_argument(
        "--max-iterations",
        type=int,
        default=100,
        help="Maximum iterative PCA rounds (default: 100).",
    )
    parser.add_argument(
        "--min-gain",
        type=float,
        default=0.01,
        help="Stop when update MSE / largest update MSE is below this value (default: 0.01).",
    )
    parser.add_argument(
        "--random-seed",
        type=int,
        default=42,
        help="Random seed for randomized PCA (default: 42).",
    )
    args = parser.parse_args()
    if args.n_components < 2:
        parser.error("--n-components must be at least 2")
    if args.max_iterations < 1:
        parser.error("--max-iterations must be at least 1")
    if not 0 < args.min_gain < 1:
        parser.error("--min-gain must be greater than 0 and less than 1")
    if not 0 <= args.random_seed < 2**32:
        parser.error("--random-seed must be between 0 and 2**32 - 1")
    return args


def load_methylation(
    methylation: sparse.spmatrix,
    value_mask: sparse.spmatrix,
) -> tuple[np.ndarray, np.ndarray]:
    """Initialize missing fractions to observed per-VMR means."""
    if not sparse.issparse(methylation):
        raise ValueError(f"The {METHYLATION_LAYER!r} layer must be sparse")
    if not sparse.issparse(value_mask):
        raise ValueError(f"The {VALUE_MASK_LAYER!r} layer must be sparse")
    if methylation.shape != value_mask.shape:
        raise ValueError("Methylation and observed-value mask shapes do not match")

    fractions = methylation.tocsr(copy=True)
    fractions.sum_duplicates()
    if not np.isfinite(fractions.data).all():
        raise ValueError("Methylation fractions contain non-finite values")
    if np.any((fractions.data < 0) | (fractions.data > 1)):
        raise ValueError("Methylation fractions must be between 0 and 1")
    fractions.eliminate_zeros()

    observed = value_mask.tocsr(copy=True)
    observed.sum_duplicates()
    if not np.isfinite(observed.data).all():
        raise ValueError(f"The {VALUE_MASK_LAYER!r} layer contains non-finite values")
    if not np.isin(observed.data, (0, 1)).all():
        raise ValueError(f"The {VALUE_MASK_LAYER!r} layer must contain only 0 and 1")
    observed.eliminate_zeros()
    observed.data = np.ones(observed.nnz, dtype=bool)

    outside_mask = fractions - fractions.multiply(observed)
    outside_mask.eliminate_zeros()
    if outside_mask.nnz:
        raise ValueError(
            f"The {METHYLATION_LAYER!r} layer contains nonzero values outside "
            f"the {VALUE_MASK_LAYER!r} layer"
        )

    observed_counts = np.asarray(observed.getnnz(axis=0)).ravel()
    if np.any(observed_counts == 0):
        raise ValueError("Every VMR needs at least one observed methylation fraction")
    feature_means = (
        np.asarray(fractions.sum(axis=0)).ravel() / observed_counts
    ).astype(np.float32)

    values = fractions.toarray().astype(np.float32, copy=False)
    missing = ~observed.toarray()
    np.copyto(values, feature_means[np.newaxis, :], where=missing)
    return values, missing


def iterative_pca_impute(
    values: np.ndarray,
    missing: np.ndarray,
    n_components: int,
    max_iterations: int,
    min_gain: float,
    random_seed: int,
    block_size: int = 2048,
) -> list[tuple[int, float, float]]:
    """Update only missing entries with bounded low-rank reconstructions."""
    history: list[tuple[int, float, float]] = []
    if not missing.any():
        return history

    largest_mse = 0.0
    for iteration in range(1, max_iterations + 1):
        pca = PCA(
            n_components=n_components,
            svd_solver="randomized",
            random_state=random_seed,
        )
        scores = pca.fit_transform(values)
        squared_error = 0.0
        missing_count = 0

        for start in range(0, values.shape[1], block_size):
            end = min(start + block_size, values.shape[1])
            block_missing = missing[:, start:end]
            if not block_missing.any():
                continue
            reconstruction = scores @ pca.components_[:, start:end]
            reconstruction += pca.mean_[start:end]
            np.clip(reconstruction, 0.0, 1.0, out=reconstruction)

            current = values[:, start:end]
            delta = reconstruction[block_missing] - current[block_missing]
            squared_error += float(np.dot(delta, delta))
            missing_count += delta.size
            current[block_missing] = reconstruction[block_missing]

        mse = squared_error / missing_count
        largest_mse = max(largest_mse, mse)
        relative_mse = mse / largest_mse if largest_mse else 0.0
        history.append((iteration, mse, relative_mse))
        print(f"Iterative PCA {iteration}: relative_mse={relative_mse:.6f}")
        if iteration > 1 and relative_mse < min_gain:
            break
    return history


def plot_imputation_history(
    path: Path,
    history: list[tuple[int, float, float]],
    min_gain: float,
) -> None:
    iterations = [row[0] for row in history]
    mse = [row[1] for row in history]
    relative_mse = [row[2] for row in history]
    figure, axes = plt.subplots(1, 2, figsize=(10, 4))
    axes[0].plot(iterations, mse, marker="o", color="#4DBBD5")
    axes[0].set_xlabel("Iteration", fontsize=10)
    axes[0].set_ylabel("MSE", fontsize=10)
    axes[0].set_title("Iterative-PCA methylation imputation", fontsize=12)
    axes[1].plot(iterations, relative_mse, marker="o", color="#4DBBD5")
    axes[1].axhline(min_gain, color="#E64B35", linestyle="--", linewidth=1)
    axes[1].set_xlabel("Iteration", fontsize=10)
    axes[1].set_ylabel("MSE / maximum MSE", fontsize=10)
    axes[1].set_title("Relative convergence", fontsize=12)
    if not history:
        for axis in axes:
            axis.text(
                0.5,
                0.5,
                "No missing values",
                ha="center",
                va="center",
                transform=axis.transAxes,
            )
    for axis in axes:
        axis.grid(alpha=0.2)
    figure.tight_layout()
    figure.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def main() -> None:
    args = parse_args()
    input_path = args.input.expanduser().resolve()
    output_path = (
        args.output.expanduser().resolve()
        if args.output
        else input_path.parent.parent / "imputed" / f"{input_path.stem}.imputed.h5ad"
    )
    convergence_path = output_path.parent / "methylation_imputation_convergence.png"
    if not input_path.is_file():
        raise SystemExit(f"Input H5AD does not exist: {input_path}")
    try:
        validate_output(output_path)
        validate_output(convergence_path)
        adata = ad.read_h5ad(input_path)
        if "cluster" not in adata.obs:
            raise ValueError("Input H5AD has no cluster labels; run stage 03 first")
        if IMPUTED_LAYER in adata.layers:
            raise ValueError(f"Input H5AD already has layer {IMPUTED_LAYER!r}")
        for layer in (METHYLATION_LAYER, VALUE_MASK_LAYER):
            if layer not in adata.layers:
                raise ValueError(f"Input H5AD is missing layer {layer!r}")
        if args.n_components >= min(adata.n_obs, adata.n_vars):
            raise ValueError(
                "--n-components must be smaller than both spot and VMR counts"
            )

        values, missing = load_methylation(
            adata.layers[METHYLATION_LAYER], adata.layers[VALUE_MASK_LAYER]
        )
        missing_count = int(missing.sum())
        print(
            f"Imputing {missing_count:,} missing fractions in "
            f"{adata.n_obs:,} spots x {adata.n_vars:,} VMRs"
        )
        history = iterative_pca_impute(
            values,
            missing,
            args.n_components,
            args.max_iterations,
            args.min_gain,
            args.random_seed,
        )
        adata.layers[IMPUTED_LAYER] = values
        output_path.parent.mkdir(parents=True, exist_ok=True)
        plot_imputation_history(convergence_path, history, args.min_gain)
        write_anndata(adata, output_path)
    except (OSError, ValueError) as error:
        raise SystemExit(f"Error: {error}") from error

    print(f"Wrote {output_path} with layer {IMPUTED_LAYER!r}")
    print(f"Imputation convergence: {convergence_path}")


if __name__ == "__main__":
    main()
